#ifndef _UPPER_LAYER_H_
#define _UPPER_LAYER_H_

enum {
    CALLBACK_DATA_INDICATION = 0,
    CALLBACK_ASSOCIATE_INDICATION,
    CALLBACK_COMM_STATUS_INDICATION,
    CALLBACK_BEACON_NOTIFY_INDICATION,
    CALLBACK_SCAN_CONFIRM,
    CALLBACK_START_CONFIRM,
    CALLBACK_MAC_RESET_CONFIRM,
    CALLBACK_MCPS_DATA_CONFIRM,
    CALLBACK_MCPS_PURGE_CONFIRM,
    CALLBACK_RX_ENABLE_CONFIRM,
    CALLBACK_SET_CONFIRM,
    CALLBACK_GET_CONFIRM,
    CALLBACK_ASSOCIATE_CONFIRM,
    CALLBACK_DISASSOCIATE_CONFIRM,
    CALLBACK_POLL_CONFIRM,
    CALLBACK_MAX_NUM,
};

typedef void (* UpperLayerCb_Type)(unsigned char *pData);

extern void UpperLayerCallbackSet(unsigned char Index, UpperLayerCb_Type Callback);
extern void UpperLayerProcess(void);

#endif /* _UPPER_LAYER_H_ */